const {Schema, model} = require("mongoose")

const Data = new Schema({
    wrench: {
        electricity: {type: Number, required: true},
        electricityOff: {type: Boolean, required: true},
        steam: {type: Number, required: true},
        steamOff: {type: Boolean, required: true},
        water: {type: Number, required: true},
        waterOff: {type: Boolean, required: true},
        air: {type: Number, required: true},
        airOff: {type: Boolean, required: true},
        workingTime: {type: Number, required: true},
        downTime: {type: Number, required: true},
        productCount: {type: Number, required: true},
        cyclopentaneCosts: {type: Number, required: true},
        electricityCosts: {type: Number, required: true},
        waterCosts: {type: Number, required: true},
    },
    cogs: {
        electricity: {type: Number, required: true},
        electricityOff: {type: Boolean, required: true},
        steam: {type: Number, required: true},
        steamOff: {type: Boolean, required: true},
        water: {type: Number, required: true},
        waterOff: {type: Boolean, required: true},
        air: {type: Number, required: true},
        airOff: {type: Boolean, required: true},
        workingTime: {type: Number, required: true},
        downTime: {type: Number, required: true},
        productCount: {type: Number, required: true},
        cyclopentaneCosts: {type: Number, required: true},
        electricityCosts: {type: Number, required: true},
        waterCosts: {type: Number, required: true},
    },
    hammer: {
        electricity: {type: Number, required: true},
        electricityOff: {type: Boolean, required: true},
        steam: {type: Number, required: true},
        steamOff: {type: Boolean, required: true},
        water: {type: Number, required: true},
        waterOff: {type: Boolean, required: true},
        air: {type: Number, required: true},
        airOff: {type: Boolean, required: true},
        workingTime: {type: Number, required: true},
        downTime: {type: Number, required: true},
        productCount: {type: Number, required: true},
        cyclopentaneCosts: {type: Number, required: true},
        electricityCosts: {type: Number, required: true},
        waterCosts: {type: Number, required: true},
    },
    rocket: {
        electricity: {type: Number, required: true},
        electricityOff: {type: Boolean, required: true},
        steam: {type: Number, required: true},
        steamOff: {type: Boolean, required: true},
        water: {type: Number, required: true},
        waterOff: {type: Boolean, required: true},
        air: {type: Number, required: true},
        airOff: {type: Boolean, required: true},
        workingTime: {type: Number, required: true},
        downTime: {type: Number, required: true},
        productCount: {type: Number, required: true},
        cyclopentaneCosts: {type: Number, required: true},
        electricityCosts: {type: Number, required: true},
        waterCosts: {type: Number, required: true},
    },
    lab: {
        electricity: {type: Number, required: true},
        electricityOff: {type: Boolean, required: true},
        steam: {type: Number, required: true},
        steamOff: {type: Boolean, required: true},
        water: {type: Number, required: true},
        waterOff: {type: Boolean, required: true},
        air: {type: Number, required: true},
        airOff: {type: Boolean, required: true},
        workingTime: {type: Number, required: true},
        downTime: {type: Number, required: true},
        productCount: {type: Number, required: true},
        cyclopentaneCosts: {type: Number, required: true},
        electricityCosts: {type: Number, required: true},
        waterCosts: {type: Number, required: true},
    }
})

module.exports = model("Data", Data)